name: mobile
description: "L and L application for drivers"

publish_to: 'none'


version: 1.0.0+1

environment:
  sdk: '>=3.4.4 <4.0.0'


dependencies:
  flutter:
    sdk: flutter

  #Utility packages
  intl: ^0.18.1
  logger: ^2.0.1
  url_launcher: ^6.1.12
  flutter_native_splash: 2.2.16
  smooth_page_indicator: ^1.1.0
  lottie: ^2.7.0
  connectivity_plus: ^5.0.1
  shimmer: ^3.0.0
  polyline_do: ^0.1.0
  flutter_polyline_points: ^2.1.0
  polyline_codec: ^0.1.6
  mapbox_polyline_points: ^0.0.5
  mapbox_gl: ^0.16.0
  http: ^1.2.2



  #icons
  cupertino_icons: ^1.0.6
  iconsax: 0.0.8

  #State management
  get: ^4.6.6
  get_storage: ^2.1.1


  #Product specific
  carousel_slider: ^4.2.1
  readmore: ^2.2.0
  flutter_rating_bar: ^4.0.1

  cached_network_image: ^3.4.0
  flutter_dotenv: ^5.1.0
  location: ^5.0.1
  flutter_mapbox_navigation: ^0.1.7


dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true

  #  Local assets:
  assets:
    - assets/logos/
    - assets/images/
    - assets/images/animations/
    - assets/images/users/
    - assets/fonts/
    - assets/icons/
    - assets/config/


  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Light.ttf
          weight: 300
        - asset: assets/fonts/Poppins-Regular.ttf
          weight: 400
        - asset: assets/fonts/Poppins-Italic.ttf
          style: italic
        - asset: assets/fonts/Poppins-Medium.ttf
          weight: 500
        - asset: assets/fonts/Poppins-MediumItalic.ttf
          weight: 500
          style: italic
        - asset: assets/fonts/Poppins-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Poppins-SemiBoldItalic.ttf
          weight: 600
          style: italic
        - asset: assets/fonts/Poppins-Bold.ttf
          weight: 700
        - asset: assets/fonts/Poppins-BoldItalic.ttf
          weight: 700
          style: italic

    - family: KumbhSans
      fonts:
        - asset: assets/fonts/KumbhSans-Light.ttf
          weight: 300
        - asset: assets/fonts/KumbhSans-Regular.ttf
          weight: 400
        - asset: assets/fonts/KumbhSans-Medium.ttf
          weight: 500
        - asset: assets/fonts/KumbhSans-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/KumbhSans-Bold.ttf
          weight: 700
        - asset: assets/fonts/KumbhSans-Black.ttf
          weight: 800



