version: '3.4'

name: landl

services:
  ll.api:
    image: ${DOCKER_REGISTRY-}llapi
    container_name: ll.api
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__PgDbConnection=Server=103.185.184.204;Port=5435;Database=LandL;User ID=postgres;Password=postgres;Trust Server Certificate=true;
    build:
      context: .
      dockerfile: L&L.API/Dockerfile
    ports:
      - "5000:5000"
      - "5001:5001"
