name: Compose Docker Cloud Project

on:
  push:
    branches:
      - main

jobs:
  docker-compose:
    runs-on: self-hosted
    environment: docker
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      
      - name: Change to server directory
        run: cd ./../../server
      
      - name: Run Docker Compose
        run: docker compose up --build -d
