name: Compose Docker cloud project

on:
  push:
    branches:
      - main

jobs:
  docker-compose:
    runs-on: self-hosted
    environment: docker
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      
      - name: Change directory to server and run Docker Compose
        run: |
          cd server
          docker compose up --build -d
